In [27]:
#Q1(Ans)
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array( list_)

print('Datatype:', array_list.dtype)
print('Datatype:', type(list_))
#array_list is an array its data types is string but list_variable is a list data types

Datatype: <U1
Datatype: <class 'list'>


In [30]:
#Q2(Ans)
for i in array_list:
    print("Data types:", array_list.dtype)

Data types: <U1
Data types: <U1
Data types: <U1
Data types: <U1
Data types: <U1


In [26]:
for i in list_:
    print("Data types:", type(i))

Data types: <class 'str'>
Data types: <class 'str'>
Data types: <class 'str'>
Data types: <class 'str'>
Data types: <class 'str'>


In [43]:
#Q3(Ans)
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print("Data types:", num_array.dtype)
print("Data types:", type(num_list))

Data types: int64
Data types: <class 'list'>


In [46]:
for i in num_array:
    for j in i:
        print("Data types:", j.dtype)

Data types: int64
Data types: int64
Data types: int64
Data types: int64
Data types: int64
Data types: int64


In [47]:
for i in num_list:
    for j in i:
        print("Data types:", type(j))

Data types: <class 'int'>
Data types: <class 'int'>
Data types: <class 'int'>
Data types: <class 'int'>
Data types: <class 'int'>
Data types: <class 'int'>


In [49]:
#Q4(Ans
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
num_array.size

6

In [51]:
np.shape(num_array)

(2, 3)

In [54]:
#Q5(Ans)
arr=np.zeros((3,3))

In [55]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
arr.shape

(3, 3)

In [57]:
arr.size

9

In [58]:
#Q6(Ans)
arr1=np.eye(5)

In [59]:
arr1


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
arr1.shape

(5, 5)

In [61]:
arr1.size

25